"""create recordings table

Revision ID: 06db10664304
Revises: ecf06b2cc23e
Create Date: 2026-02-18 21:10:20.028079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06db10664304'
down_revision: Union[str, Sequence[str], None] = 'ecf06b2cc23e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recordings',
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=False),
    sa.Column('transcript_raw', sa.String(), nullable=True),
    sa.Column('transcript_normalized', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recordings_visit_id', 'recordings', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_recordings_visit_id', table_name='recordings')
    op.drop_table('recordings')
    # ### end Alembic commands ###
