"""create doctor_decisions table

Revision ID: 24f7b3299862
Revises: 84664773464b
Create Date: 2026-02-18 21:32:41.395001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f7b3299862'
down_revision: Union[str, Sequence[str], None] = '84664773464b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_decisions',
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis', sa.String(), nullable=True),
    sa.Column('prescribed_medication', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('ai_agreement', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_decision_visit_id', 'doctor_decisions', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_decision_visit_id', table_name='doctor_decisions')
    op.drop_table('doctor_decisions')
    # ### end Alembic commands ###
