"""create override_logs table

Revision ID: 4112a06986dd
Revises: 24f7b3299862
Create Date: 2026-02-18 21:41:56.951154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4112a06986dd'
down_revision: Union[str, Sequence[str], None] = '24f7b3299862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('override_logs',
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('overridden_field', sa.String(), nullable=False),
    sa.Column('original_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('doctor_id', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_override_visit_id', 'override_logs', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_override_visit_id', table_name='override_logs')
    op.drop_table('override_logs')
    # ### end Alembic commands ###
