"""create visits table

Revision ID: ecf06b2cc23e
Revises: e5dcc7c33678
Create Date: 2026-02-18 21:00:23.232578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecf06b2cc23e'
down_revision: Union[str, Sequence[str], None] = 'e5dcc7c33678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('visit_status', sa.Enum('REGISTERED', 'INTAKE_COMPLETED', 'AI_PROCESSED', 'DOCTOR_REVIEWED', 'CLOSED', name='visitstatus'), nullable=False),
    sa.Column('urgency_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='urgencylevel'), nullable=True),
    sa.Column('language_detected', sa.String(), nullable=True),
    sa.Column('chief_complaint', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_visits_patient_id', 'visits', ['patient_id'], unique=False)
    op.create_index('idx_visits_status', 'visits', ['visit_status'], unique=False)
    op.create_index('idx_visits_urgency', 'visits', ['urgency_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_visits_urgency', table_name='visits')
    op.drop_index('idx_visits_status', table_name='visits')
    op.drop_index('idx_visits_patient_id', table_name='visits')
    op.drop_table('visits')
    # ### end Alembic commands ###
